### ISSUE TITLE
사용자 인증

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#1]
### Todo

- [x] 이메일 로그인 기능
- [x] 이메일 회원가입 기능
  - [x]  회원가입 시 이메일, 비밀번호, 전화번호는 유효성 검사를 한다.
    - **비밀번호 최소 길이**
        - 최소 10자리 이상 : 영어 대문자, 소문자, 숫자, 특수문자 중 2종류 문자 조합으로 구성
        - 최소 8자리 이상 : 영어 대문자, 소문자, 숫자, 특수문자 중 3종류 문자 조합으로 구성
- [x] 소셜 로그인 기능
- [x] 로그아웃 기능
- [x] 라우터 접근 제한 설정
  - [x] React router를 사용해 Public(비로그인)과 Private(로그인) 클라이언트 페이지들을 설계
  - [x]  판매자와 구매자 페이지 구분:
            - 판매자 계정으로 로그인한 사용자는 판매 관련 페이지 (상품 등록, 판매 기록 관리)에 접근 가능
            - 구매자 계정으로 로그인한 사용자는 구매 관련 페이지 (상품 검색, 구매 이력 확인)에 접근 가능

### 작업 기간

2024.04.19
