### ISSUE TITLE
장바구니 CRUD

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#10]
### Todo

- [x] 결제 대기 페이지 레이아웃 설계
- [x] 장바구니 페이지 레이아웃 설계
- [x] 장바구니 조회 기능
- [x] 장바구니 추가 기능
  - 중복된 상품이 추가되지 않게 주의
- [x] 장바구니 수정 기능
- [x] 장바구니 삭제 기능

### 작업 기간

2024.04.27 ~ 2024.04.29
