### ISSUE TITLE
이벤트 결제

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#13]
### Todo

- [x] 이벤트 결제 페이지 레이아웃 설계
- [x] 이벤트 결제 완료 페이지 레이아웃 설계
- [x] 결제 SDK를 활용한 결제 로직 구현

### 작업 기간

2024.04.30 ~ 2024.05.02

<br />

## 참고 자료 (optional)

https://developers.portone.io/docs/ko/authpay/guide?v=v2
