### ISSUE TITLE
이벤트 참여 내역

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#17]
### Todo

- [x] 마이페이지 - `이벤트 참여 내역` 탭 레이아웃 구현
- [x] 이벤트 참여 내역 조회
  - [x] 최신순으로 정렬하여 페이지네이션 구현
- [x] 구매 취소 기능
  - [x] 취소한 ORDER는 DB에서 삭제하지 않고 ORDER의 상태만 CANCLED로 변경

### 작업 기간

2024.05.03 ~ 2024.05.04
