### ISSUE TITLE
E2E 테스트

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#21]
### Todo

**1. 인증**

- [x]  **이메일 로그인**: 올바른 이메일/비밀번호 입력 및 잘못된 정보 입력 시의 에러 처리 확인.
- [x]  **이메일 회원가입**: 회원가입 폼이 적절한 입력 값을 받고 처리하는지, 필수 필드에 대한 검증이 이루어지는지 확인.
- [x]  **로그아웃**: 로그아웃 기능이 제대로 동작하는지 검사.
- [x]  **접근 제한 기능**: 사용자의 권한에 따라 접근 제한 기능이 제대로 동작하는지 검사.

**2. 이벤트 목록 및 검색 기능**

- [x]  **이벤트 목록 조회**: 이벤트 목록이 올바르게 표시되는지 검사.
- [x] **정렬 옵션**: 최신 순, 인기 순 정렬 옵션을 통해 목록이 올바르게 정렬되어 나타나는지 검사.
- [x]  **필터 검색**: 카테고리, 날짜, 가격 등 다양한 필터 옵션을 적용했을 때, 결과가 기대하는 대로 필터링 되는지 확인.

**3. 이벤트 상세 페이지**

- [x]  **이벤트 상세 정보 확인**: 페이지가 로드될 때 모든 상세 정보(장소, 시간, 주최자 정보 등)가 정확하게 표시되는지 검사.
- [x]  **참여 신청 기능**: 이벤트 참여 신청 버튼이 올바르게 동작하는지 확인.
- [x] **찜하기 기능**: 찜하기 버튼이 올바르게 동작하는지 확인.

**4. 장바구니 기능 테스트**

- [x]  장바구니에 아이템 추가: 사용자가 이벤트 티켓을 장바구니에 추가할 수 있는지 검증.
- [ ]  장바구니 아이템 수량 조절: 사용자가 장바구니 내 아이템의 수량을 조절할 수 있는지 검사.
- [ ]  장바구니 아이템 제거: 사용자가 아이템 제거 버튼을 클릭하면, 해당 아이템이 장바구니에서 제거되고, 총 가격이 적절히 조정되는지 확인.
- [ ]  장바구니에서 결제로 이동: 장바구니에 모든 아이템을 추가한 후, 결제 페이지로 넘어갈 수 있는지 검사.

**5. 결제 프로세스**

- [x]  **티켓 선택 및 결제**: 이벤트 티켓 선택 후 결제 페이지로 넘어가지는지 검사.
- [ ]  **결제 완료 후 결과 확인**: 결제 완료 후 사용자가 구매 내역을 확인할 수 있는지 테스트.

**6. 마이 페이지 기능**

- [ ]  **프로필 정보 수정**: 사용자 정보 수정 기능이 잘 작동하는지 확인.
- [ ]  **이벤트 관리 및 주문 상태 관리**: 이벤트 등록, 수정, 삭제 및 주문 상태 업데이트가 원활히 이루어지는지 검증.

### 작업 기간

2024.05.06 ~ 2024.05.08

<br />

## 참고 자료

> https://www.youtube.com/watch?v=u8vMu7viCm8
https://velog.io/@sangwoong/Cypress-Cypress-Settings
https://velog.io/@sangwoong/Cypress-Cypress-Code-with-commands
