### ISSUE TITLE
렌더링 최적화

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#24]
### Todo

- [x] React DevTools 프로파일러를 사용한 컴포넌트 렌더링 성능 분석
- [x] 리렌더링 야기할 수 있는 함수 useCallback으로 캐싱하기
- [ ] Cumputation cost가 큰 계산이 있다면 (필터 리스트 등) 리렌더링 사이의 계산 결과를 useMemo로 캐싱하기
- [x] 불필요한 리렌더링이 일어날 수 있는 부분을 찾아 React.memo로 컴포넌트 메모화 하기

### 작업 기간

2024.05.09
