### ISSUE TITLE
이벤트 CRUD

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#3]
### Todo

- [x] 마이페이지 - `이벤트 관리` 페이지 레이아웃 구현
- [x] 이벤트 등록 기능
- [x] 이벤트 수정 기능
- [x] 이벤트 삭제 기능

### 작업 기간

2024.04.20 ~ 2024.04.23
