### ISSUE TITLE
단위 테스트

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#40]
### Todo

- [ ] Jest, React Testing Library를 통한 단위 테스트 코드 작성
  - [x] 유틸리티 함수 테스트
  - [x] 재사용 컴포넌트 테스트
  - [ ] 외부 의존성 테스트

### 작업 기간

2024.05.11 ~ 2024.05.14
