### ISSUE TITLE
이벤트 목록

### ISSUE THREAD

**Issue by soprue** [soprue/eventrix#5]
### Todo

- [x] 이벤트 목록 페이지 레이아웃 구현
  - [x] 최신 순/인기 순 정렬 기능
  - [x] 카테고리/가격 필터링 기능
- [x] 검색 결과 페이지 레이아웃 구현
  - [x] 검색 기능

### 작업 기간

2024.04.23 ~ 2024.04.24
